# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#



# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

xcversion(version: "9.2") # Selects Xcode 9.2
xcode_select "/Applications/Xcode.app"

default_platform(:ios)

platform :ios do
  desc "screen shot and give a device frame to it,finally upload to app store"
    lane :screenshots_upload do
    capture_screenshots
    frame_screenshots(white: true)
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh    
    build_app
    upload_to_app_store
  end
 
  desc "screen shot only"
    lane :screenshots do
    capture_screenshots
  end  


  desc "build and upload"
    lane :build_release do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app
    upload_to_app_store  
  end
end


